[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true
orderLiterals = true
deduplicate = true
cse = true
constantOptimizer = true

[rpc_endpoints]
og_testnet = "https://evmrpc-testnet.0g.ai"

[etherscan]
og_testnet = { api_url = "https://api.chainscan-galileo.0g.ai/api", key = "${ETHERSCAN_API_KEY}" }

